import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import {
  StyledComponentsRegistry,
  ClientLayout,
} from '@/components/configs/StyledComponentsConfig';
import AppWrapper from '@/components/layouts/AppWrapper';
import QueryClientProvider from '@/components/configs/TanstackQueryConfig/ClientQueryProvider';

const InterRegular = Inter({
  variable: '--font-inter-regular',
  weight: '400',
  style: 'normal',
  display: 'swap',
  subsets: ['latin'],
});

const InterMedium = Inter({
  variable: '--font-inter-medium',
  weight: '500',
  style: 'normal',
  display: 'swap',
  subsets: ['latin'],
});

const InterSemiBold = Inter({
  variable: '--font-inter-semibold',
  weight: '600',
  style: 'normal',
  display: 'swap',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${InterRegular.variable} ${InterMedium.variable} ${InterSemiBold.variable}`}
      >
        <StyledComponentsRegistry>
          <ClientLayout>
            <QueryClientProvider>
              <AppWrapper>{children}</AppWrapper>
            </QueryClientProvider>
          </ClientLayout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
