import { PropertyProps } from './types/properties';

export const dummyProperties: PropertyProps[] = [
  {
    imageUrl: '/images/properties/a.jpg',
    price: '€450,000',
    address: '123 Main Street, Dublin, Ireland',
    size: 120,
    bedrooms: 3,
    bathrooms: 2,
    garages: 1,
    href: '/properties/123-main-st',
    tags: ['for-sale', 'verified', 'featured', 'new'],
  },
  {
    imageUrl: '/images/properties/b.jpg',
    price: '€375,000',
    address: '45 Oak Lane, Galway, Ireland',
    size: 95,
    bedrooms: 2,
    bathrooms: 1,
    garages: 1,
    href: '/properties/45-oak-ln',
    tags: ['for-rent', 'new'],
  },
  {
    imageUrl: '/images/properties/c.jpg',
    price: '€610,000',
    address: '78 Riverwalk Drive, Cork, Ireland',
    size: 135,
    bedrooms: 4,
    bathrooms: 3,
    garages: 2,
    href: '/properties/78-riverwalk',
    tags: ['rent-to-own', 'verified'],
  },
  {
    imageUrl: '/images/properties/d.jpg',
    price: '€490,000',
    address: '19 Seaside Blvd, Wexford, Ireland',
    size: 110,
    bedrooms: 3,
    bathrooms: 2,
    garages: 1,
    href: '/properties/19-seaside-blvd',
    tags: ['shared-accommodation', 'featured'],
  },
  {
    imageUrl: '/images/properties/e.jpg',
    price: '€520,000',
    address: '5 Forest Hill, Limerick, Ireland',
    size: 130,
    bedrooms: 4,
    bathrooms: 2,
    garages: 2,
    href: '/properties/5-forest-hill',
    tags: ['for-auction', 'new', 'verified'],
  },
  {
    imageUrl: '/images/properties/f.jpg',
    price: '€410,000',
    address: '34 Glenview Road, Kilkenny, Ireland',
    size: 105,
    bedrooms: 3,
    bathrooms: 2,
    garages: 1,
    href: '/properties/34-glenview',
    tags: ['for-sale'],
  },
  {
    imageUrl: '/images/properties/g.jpg',
    price: '€580,000',
    address: '88 Parkside Avenue, Sligo, Ireland',
    size: 140,
    bedrooms: 5,
    bathrooms: 3,
    garages: 2,
    href: '/properties/88-parkside',
    tags: ['for-rent', 'verified', 'featured'],
  },
  {
    imageUrl: '/images/properties/h.jpg',
    price: '€360,000',
    address: '12 Meadow Lane, Waterford, Ireland',
    size: 92,
    bedrooms: 2,
    bathrooms: 1,
    garages: 1,
    href: '/properties/12-meadow',
    tags: ['shared-accommodation', 'new'],
  },
];
